project:
  type: book

book:
  title: "Secondary Malaria Data Sources"
  author: "Amir Siraj"
  date: "10/30/2024"
  chapters:
    - index.qmd
    - module_01.qmd
    - module_02.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

